lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - assets/sendmail_template.txt
    - .github/workflows/linting.yml
  multiqc_config: false
nf_core_version: 4.0.3
repository_type: pipeline
template:
  author: Jose Nimo
  description: Processing, segmentation and quantification of H&E and multiplex immunofluorescence images
  force: false
  is_nfcore: false
  name: histo
  org: josenimo
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 0.1.0dev
