#!/usr/bin/env python3
"""Generate (or verify) containers.tsv, the list of every image this pipeline needs.

Why this exists: pre-staging images onto the cluster means knowing the complete
set in advance, and that set is currently spread across fifteen `main.nf` files
in a two-branch conditional. Reading it by eye is exactly the kind of manual step
that silently goes stale after a module update.

The manifest is keyed on the *image*, not the module, because several modules
share one image. Fifteen modules currently need far fewer than fifteen pulls, and
that difference is the whole point when each image is gigabytes over a slow link.

This lives in tools/ rather than bin/ deliberately: bin/ is staged onto the PATH
of every pipeline task, and development tooling has no business being there.

Usage:
    tools/container_manifest.py            # rewrite containers.tsv
    tools/container_manifest.py --check    # exit 1 if containers.tsv is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "containers.tsv"

HEADER = ["singularity_uri", "docker_uri", "conda", "modules"]

# The container directive spans several lines and holds two quoted URIs in a
# ternary. Grab the whole directive, then pull the quoted strings out of it.
CONTAINER_BLOCK = re.compile(
    r"^\s*container\s+(.*?)(?=^\s*(?:input|output|script|stub|when|label|tag|conda|publishDir|process|\})\b)",
    re.MULTILINE | re.DOTALL,
)
QUOTED = re.compile(r"'([^']+)'")
SIMPLE = re.compile(r"^\s*container\s+['\"]([^'\"]+)['\"]\s*$", re.MULTILINE)


def conda_spec(module_dir: Path) -> str:
    """The conda environment is the human-readable statement of what the image is."""
    env = module_dir / "environment.yml"
    if not env.exists():
        return ""
    deps = []
    in_deps = False
    for line in env.read_text().splitlines():
        if line.strip().startswith("dependencies:"):
            in_deps = True
            continue
        if in_deps:
            if line.strip().startswith("-"):
                deps.append(line.strip().lstrip("-").strip())
            elif line.strip() and not line.startswith((" ", "\t")):
                break
    return ",".join(deps)


def extract(main_nf: Path) -> tuple[str, str]:
    """Return (singularity_uri, docker_uri) for one module."""
    text = main_nf.read_text()

    simple = SIMPLE.search(text)
    if simple and "${" not in simple.group(1):
        uri = simple.group(1)
        return ("", uri)

    block = CONTAINER_BLOCK.search(text)
    if not block:
        return ("", "")

    uris = [u for u in QUOTED.findall(block.group(1)) if "/" in u and " " not in u]
    singularity = next((u for u in uris if u.startswith("http")), "")
    docker = next((u for u in uris if not u.startswith("http")), "")
    return (singularity, docker)


def collect() -> list[list[str]]:
    # Keyed on the image pair so that modules sharing an image collapse to one row.
    by_image: dict[tuple[str, str], dict] = defaultdict(lambda: {"conda": set(), "modules": set()})

    for main_nf in sorted(REPO.glob("modules/**/main.nf")):
        singularity, docker = extract(main_nf)
        if not (singularity or docker):
            continue
        module = main_nf.parent.relative_to(REPO).as_posix()
        entry = by_image[(singularity, docker)]
        entry["modules"].add(module)
        spec = conda_spec(main_nf.parent)
        if spec:
            entry["conda"].add(spec)

    rows = []
    for (singularity, docker), entry in by_image.items():
        rows.append(
            [
                singularity,
                docker,
                ";".join(sorted(entry["conda"])),
                ",".join(sorted(entry["modules"])),
            ]
        )
    # Sorted on the docker URI: it is the readable one, and it keeps the file
    # diffable when a single image is bumped.
    return sorted(rows, key=lambda r: (r[1], r[0]))


def render(rows: list[list[str]]) -> str:
    lines = [
        "# Every container image this pipeline needs, one row per image.",
        "# GENERATED by tools/container_manifest.py -- do not edit by hand.",
        "# Regenerate after any module add, remove or container bump.",
        "\t".join(HEADER),
    ]
    lines += ["\t".join(r) for r in rows]
    return "\n".join(lines) + "\n"


def cache_filename(uri: str) -> str:
    """The exact filename Nextflow will look for in NXF_SINGULARITY_CACHEDIR.

    Mirrors Nextflow's SingularityCache.simpleName: drop the scheme, replace ':'
    and '/' with '-', append '.img'. Reproduced rather than approximated on
    purpose. An earlier version of this check matched on the tool name and
    version appearing anywhere in a directory listing, and reported an image as
    present when the cache held it under a different URI's name --
    `labsyspharm-unetcoreograph-2.4.6.img` when Nextflow wanted
    `docker.io-labsyspharm-unetcoreograph-2.4.6.img`. Same image, same version,
    and Nextflow still went to the network for it mid-run.
    """
    p = uri.find("://")
    name = uri[p + 3 :] if p != -1 else uri
    ext = ".img"
    if ".sif:" in name:
        ext, name = ".sif", name.replace(".sif:", "-")
    elif name.endswith(".sif"):
        ext, name = ".sif", name[:-4]
    return name.replace(":", "-").replace("/", "-") + ext


def check_cache(rows: list[list[str]], cachedir: Path) -> int:
    missing = []
    print(f"cache: {cachedir}\n")
    for singularity, docker, _conda, modules in rows:
        # Under a singularity profile Nextflow prefers the https URI when the
        # module offers one, and falls back to the docker URI otherwise.
        uri = singularity or docker
        want = cache_filename(uri)
        target = cachedir / want
        # exists() follows symlinks, which is what Nextflow needs too: a dangling
        # symlink is a miss even though `ls` shows the name.
        if target.exists():
            print(f"  ok      {want}")
        else:
            print(f"  MISSING {want}")
            missing.append((want, uri, modules, target.is_symlink()))

    if not missing:
        print(f"\nAll {len(rows)} images present. No runtime pull will happen.")
        return 0

    print(f"\n{len(missing)} image(s) missing. Nextflow WILL pull these at run time,")
    print("which on this cluster means a long job dying at an unpredictable point.\n")
    for want, uri, modules, dangling in missing:
        print(f"  {want}")
        print(f"    needed by : {modules}")
        if dangling:
            print("    NOTE      : a symlink of this name exists but its target is gone")
        if uri.startswith("http"):
            print(f"    fetch     : singularity pull --dir '{cachedir}' '{want}' '{uri}'")
        else:
            print(f"    fetch     : singularity pull --dir '{cachedir}' '{want}' 'docker://{uri}'")
    print("\nIf the image is already in the cache under a different name, symlink rather")
    print("than re-pull; Nextflow resolves symlinks:")
    print(f"  ln -s <existing>.img '{cachedir}/{missing[0][0]}'")
    return 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify the manifest is current")
    ap.add_argument(
        "--check-cache",
        metavar="DIR",
        nargs="?",
        const="",
        help="verify every image is in the Singularity cache under the exact "
        "name Nextflow expects (default: $NXF_SINGULARITY_CACHEDIR)",
    )
    args = ap.parse_args()

    rows = collect()
    if not rows:
        print(
            "No containers found. The parser is probably broken, which is worse "
            "than an empty pipeline; refusing to write an empty manifest.",
            file=sys.stderr,
        )
        return 1

    content = render(rows)

    if args.check_cache is not None:
        import os

        cachedir = args.check_cache or os.environ.get("NXF_SINGULARITY_CACHEDIR", "")
        if not cachedir:
            print("NXF_SINGULARITY_CACHEDIR is not set and no directory was given.", file=sys.stderr)
            return 2
        return check_cache(rows, Path(cachedir))

    if args.check:
        current = MANIFEST.read_text() if MANIFEST.exists() else ""
        if current != content:
            print(
                f"{MANIFEST.name} is out of date. Run tools/container_manifest.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{MANIFEST.name} is current ({len(rows)} images).")
        return 0

    MANIFEST.write_text(content)
    n_modules = sum(len(r[3].split(",")) for r in rows)
    print(f"Wrote {MANIFEST.name}: {len(rows)} images for {n_modules} modules.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
